name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: skywarth/vite-github-pages-deployer@v1.5.0
        with:
          public_base_path: '/huddle-landing-page/'
          build_path: './dist'
          package_manager: 'npm'